[package]
name = "alpha_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
askama_axum = "0.4.0"
axum = "0.7.5"
tokio = "1.39.2"
tower-http = "0.5.2"

[build-dependencies]
askama = "0.12.0"

[package.metadata.askama]
template_dir = "templates"
